services:
  jenkins:
    build: .
    user: root  # needed for playwright install --with-deps
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - URL=${URL}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - APPLITOOLS_KEY=${APPLITOOLS_KEY}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - CASC_JENKINS_CONFIG=/var/jenkins_config/casc.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_config/casc.yaml

volumes:
  jenkins_home:
