jenkins:
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_USER}"
          password: "${JENKINS_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: |
      pipelineJob('printup') {
        parameters {
          choiceParam('BROWSER', ['chrome', 'firefox', 'edge'], 'Browser to run tests')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/ilyar88/Printup-project.git') }
                branch('main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              id: "PRINTUP_URL"
              secret: "${URL}"
              description: "PrintUp URL"
          - string:
              id: "PRINTUP_EMAIL"
              secret: "${EMAIL}"
              description: "PrintUp Email"
          - string:
              id: "PRINTUP_PASSWORD"
              secret: "${PASSWORD}"
              description: "PrintUp Password"
          - string:
              id: "PRINTUP_NEW_PASSWORD"
              secret: "${NEW_PASSWORD}"
              description: "PrintUp New Password (forgot-password flow)"
          - string:
              id: "PRINTUP_APP_PASSWORD"
              secret: "${APP_PASSWORD}"
              description: "Gmail App Password (forgot-password flow IMAP)"
          - string:
              id: "PRINTUP_APPLITOOLS_KEY"
              secret: "${APPLITOOLS_KEY}"
              description: "Applitools Key"
